_target_: "diffusion.dataset.SimpleDataModule"
_recursive_: False

train_dataset_cfg:
  _target_: "diffusion.dataset.wiki_dataset.ContextualSST2Dataset"
  max_length: 96
  train: True

valid_dataset_cfg:
  _target_: "diffusion.dataset.wiki_dataset.ContextualSST2Dataset"
  max_length: 96
  train: False

train_dataloader_cfg:
  _target_: "torch.utils.data.DataLoader"
  batch_size: 512
  num_workers: 32
  drop_last: True
  shuffle: True

valid_dataloader_cfg:
  _target_: "torch.utils.data.DataLoader"
  batch_size: ${datamodule.train_dataloader_cfg.batch_size}
  num_workers: ${datamodule.train_dataloader_cfg.num_workers}
  drop_last: False
  shuffle: False
