_target_: "diffusion.dataset.GlueDataModule"

train_dataset_cfg:
  _target_: "diffusion.dataset.QQPGlueDataset"
  max_length: 128
  train: True

valid_dataset_cfg:
  _target_: "diffusion.dataset.QQPGlueDataset"
  max_length: ${datamodule.train_dataset_cfg.max_length}
  train: False

train_dataloader_cfg:
  _target_: "torch.utils.data.DataLoader"
  batch_size: 512
  num_workers: 16
  drop_last: True
  shuffle: True

valid_dataloader_cfg:
  _target_: "torch.utils.data.DataLoader"
  batch_size: ${datamodule.train_dataloader_cfg.batch_size}
  num_workers: ${datamodule.train_dataloader_cfg.num_workers}
  drop_last: False
  shuffle: False
