_target_: "diffusion.lightning_wrappers.contextual_denoising.ContextualDenoising"
defaults:
  - optim_partial/adam
  - sched_partial/linear_warmup
  - enc_normalizer_cfg/wiki_pret@noisy_enc_normalizer_cfg
  - enc_normalizer_cfg/wiki_t5@clean_enc_normalizer_cfg

ce_coef: 0.1